//! The outward aggregation manifest (`project.yaml`).
//!
//! Split from bootstrap so "change the manifest format" and "change the
//! CLAUDE.md takeover surface" are different files (they attract unrelated
//! edits). Contract: the engine owns only the `phase` / `progress` /
//! `updated` lines and syncs them by targeted line replacement — every other
//! line (including comments and hand edits) is the user's and survives.

use chrono::Local;

use crate::error::Result;
use crate::workspace::atomic::atomic_write;
use crate::workspace::context::ProjectContext;
use crate::workspace::layout::WorkspacePaths;
use crate::workspace::tasks::{compute_counts, Task};
use crate::workspace::workflow::WorkflowStatus;

pub(crate) fn render_manifest(ctx: &ProjectContext, phase_title: &str) -> String {
    let owner = std::env::var("NEXTUP_OWNER")
        .or_else(|_| std::env::var("USERNAME"))
        .or_else(|_| std::env::var("USER"))
        .unwrap_or_else(|_| "owner".into());
    let one_liner = if ctx.description.trim().is_empty() {
        ctx.name.clone()
    } else {
        ctx.description.lines().next().unwrap_or(&ctx.name).trim().to_string()
    };
    let now = Local::now();
    format!(
        r#"# ── {name} manifest ─────────────────────────────────────────
# Generated by Agent NextUp. The engine keeps the phase / progress / updated fields
# in sync by replacing those lines only; every other field and comment is
# left alone and maintained by hand.
id: {id}
name: {name}
one_liner: {one_liner}
status: active
phase: {phase}
next_action:
blocked_on:
progress: 0
priority: medium
owner: {owner}
started: {started}
updated: {updated}

work_record_dir: work_record/

entry_docs:
  - CLAUDE.md
  - .nextup/snapshots/latest_handoff.md

depends_on: []
provides: []
"#,
        name = yaml_safe(&ctx.name),
        id = kebab_id(&ctx.name),
        one_liner = yaml_safe(&one_liner),
        phase = yaml_safe(phase_title),
        owner = yaml_safe(&owner),
        started = now.format("%Y-%m"),
        updated = now.format("%Y-%m-%d"),
    )
}

/// Replace only the top-level `phase:` / `progress:` / `updated:` lines,
/// leaving every other line (including comments and hand edits) untouched.
pub(crate) fn sync_manifest(
    paths: &WorkspacePaths,
    tasks: &[Task],
    workflow: Option<&WorkflowStatus>,
) -> Result<()> {
    let path = paths.manifest_file();
    if !path.is_file() {
        return Ok(());
    }
    let counts = compute_counts(tasks);
    let progress = if counts.total == 0 {
        0
    } else {
        (counts.done * 100) / counts.total
    };
    let phase = workflow.map(|ws| {
        if ws.workflow.state.completed {
            "complete".to_string()
        } else {
            ws.current_phase_title()
        }
    });

    let content = std::fs::read_to_string(&path)?;
    let mut changed = false;
    let mut lines: Vec<String> = Vec::new();
    for line in content.lines() {
        let replaced = if line.starts_with("progress:") {
            Some(format!("progress: {progress}"))
        } else if line.starts_with("updated:") {
            Some(format!("updated: {}", Local::now().format("%Y-%m-%d")))
        } else if line.starts_with("phase:") {
            phase.as_ref().map(|p| format!("phase: {}", yaml_safe(p)))
        } else {
            None
        };
        match replaced {
            Some(new_line) if new_line != line => {
                changed = true;
                lines.push(new_line);
            }
            Some(same) => lines.push(same),
            None => lines.push(line.to_string()),
        }
    }
    if changed {
        let mut out = lines.join("\n");
        out.push('\n');
        atomic_write(&path, out.as_bytes())?;
    }
    Ok(())
}

/// kebab-ish id: unicode alphanumerics kept (CJK names stay readable),
/// everything else collapses to single dashes.
pub fn kebab_id(name: &str) -> String {
    let mut id = String::with_capacity(name.len());
    let mut last_dash = true; // suppress leading dash
    for ch in name.trim().chars() {
        if ch.is_alphanumeric() {
            for lower in ch.to_lowercase() {
                id.push(lower);
            }
            last_dash = false;
        } else if !last_dash {
            id.push('-');
            last_dash = true;
        }
    }
    let id = id.trim_end_matches('-').to_string();
    if id.is_empty() {
        "nextup-project".into()
    } else {
        id
    }
}

/// Plain-scalar YAML safety: colons would change parsing, so swap for the
/// fullwidth variant. Values here are display strings, not machine keys.
fn yaml_safe(value: &str) -> String {
    value.replace(':', "：").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::security::keystore::StaticKeyProvider;
    use crate::workspace::init::{initialize_project, InitProjectParams};
    use crate::workspace::ops::{create_task, update_task_status};
    use crate::workspace::tasks::{NewTask, TaskStatus};

    #[test]
    fn kebab_ids() {
        assert_eq!(kebab_id("My Project 2!"), "my-project-2");
        assert_eq!(kebab_id("年度研究計畫"), "年度研究計畫");
        assert_eq!(kebab_id("  A__B  "), "a-b");
        assert_eq!(kebab_id("!!!"), "nextup-project");
    }

    #[test]
    fn manifest_sync_touches_only_volatile_lines() {
        let dir = tempfile::tempdir().unwrap();
        initialize_project(
            &InitProjectParams {
                root: dir.path().to_string_lossy().into_owned(),
                name: "manifest-test".into(),
                domain: "coding".into(),
                description: String::new(),
                goals: vec![],
                boundaries: vec![],
                ..Default::default()
            },
            &StaticKeyProvider([9u8; 32]),
            "0.1.0",
        )
        .unwrap();
        let paths = WorkspacePaths::new(dir.path());

        // Hand edits: priority + a custom comment must survive.
        let manifest = std::fs::read_to_string(paths.manifest_file()).unwrap();
        let edited = manifest
            .replace("priority: medium", "priority: high")
            .replace("next_action:", "next_action: finish the first task # hand-written comment");
        std::fs::write(paths.manifest_file(), &edited).unwrap();

        let id = create_task(&paths, "0.1.0", NewTask {
            title: "t".into(),
            priority: 0,
            ..Default::default()
        })
        .unwrap()
        .id;
        update_task_status(&paths, "0.1.0", &id, TaskStatus::Done, None).unwrap();

        let synced = std::fs::read_to_string(paths.manifest_file()).unwrap();
        assert!(synced.contains("priority: high"), "hand-edited field survives");
        assert!(synced.contains("hand-written comment"), "comments survive");
        assert!(synced.contains("progress: 100"), "progress derived from done tasks");
        assert!(synced.contains(&format!("updated: {}", Local::now().format("%Y-%m-%d"))));
    }
}
